$(document).ready(function(){
    $(".owl-carousel").owlCarousel({
        margin:20,
        items:3,
        loop:true,
        autoplayHoverPause:true,
        autoplay:true,
        autoplayTimeout:3000,
        responseresponsiveRefreshRate:true,
        responsive:{
            0:{
                items:1,
            },
            575.98:{
                items:1,
            },
            767.98:{
                items:2,
            },
            991.98:{
                items:3
            },
            1199.98:{
                items:4,
            },
            1919.98:{
                items:4,
            }

        }
    });
})